---
- hosts: all
  gather_facts: no
  
 
  
  tasks:
  - name: Uploads requirements.txt
    template:
      src: ../utils/requirements.txt
      dest: ~/requirements.txt

  - name: Install python dependencies
    pip:
      requirements: ~/requirements.txt
      executable: pip3.7
      extra_args: --user --no-cache

  - name: Upload script
    template:
      src: ../utils/streaming-data-mock.py
      dest: ~/streaming-script.py
  
  - name: Kill previous python3 scripts (Dangerous, could kill other python3 scripts)
    command: killall python3

  - name: Run script 
    shell: cd ~; nohup python3 streaming-script.py </dev/null >/dev/null 2>&1 &
    environment: 
      S3_BUCKET_NAME: 'fog-datasets'
      S3_KEY: 'streaming-data-mock.csv'
      S3_OUTPUT_DIRECTORY: 'streaming-data-mock'

    