secret_key="secret-key"
access_key="access-key"
account_id="aws-account-id"
deepar_endpoint_name="deep-ar"
mp_endpoint_name="mean-predictor"
data_aggregation_frequency="5min" // Please stick to minutes for compatibility reasons
chatbot_url="chatbot_url" // Url of the API provided by the chatbot team. Used to plug our pipeline with their chatbot!
slack_url="slack_url"  // Slack url where to send slack messages
slack_authorization_token="token"
bmw-bucket="fog-bigdata-bmw-data"