rm -rf output/ && python tf-train.py --train_data_path "dataset/train.csv" \
                 --data_dir_path "dataset" \
                 --model_dir "output/" \
                 --train_batch_size 100 \
                 --eval_batch_size 100 \
                 --learning_rate 0.01 \
                 --train_steps 1000 \
                 --eval_steps 100 \
                 --sequence_length 50 \
                 --model "linear" \
                 --eval_delay_secs 10\
                 --min_eval_frequency 10